//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nagarro.EmployeePortal.EntityDataModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.IssueHistories = new HashSet<IssueHistory>();
            this.IssueHistories1 = new HashSet<IssueHistory>();
            this.Issues = new HashSet<Issue>();
            this.Notices = new HashSet<Notice>();
            this.Users = new HashSet<User>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<IssueHistory> IssueHistories { get; set; }
        public virtual ICollection<IssueHistory> IssueHistories1 { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<Notice> Notices { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
